// config.js
require("dotenv").config();

module.exports = {
  MONGO_URI: process.env.MONGO_URI,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  REACT_APP_FRONTEND_URL: process.env.REACT_APP_FRONTEND_URL,
  SECRET_KEY: process.env.SECRET_KEY,
  CONCIERGE_MAIL_USER: process.env.CONCIERGE_MAIL_USER,
  CONCIERGE_MAIL_PASS: process.env.CONCIERGE_MAIL_PASS,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  BELEEF_ADMIN_MAIL_USER: process.env.BELEEF_ADMIN_MAIL_USER,
  BELEEF_ADMIN_MAIL_PASS: process.env.BELEEF_ADMIN_MAIL_PASS,
  STRIPE_TEST_SECRET_KEY: process.env.STRIPE_TEST_SECRET_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
};
